def norm (x, y, z) √(x*x + y*y +z*z);
print norm(2+1, 3+1, 1);

def by_pi(n) n*π;

def fact(n) if n lt 2 then 1; else n * fact(n - 1);
c[5]= cos(88);
b = (5 ne 6);
print b;
z=if not b then print 8888; else print 9999;
print z;
if not z eq 8888 then {
   print √5555;
   }
g = by_pi(2);
print g;
for i = 1 to 3  print by_pi(i);
	
for i = 7 to 10 {
   j = i - (-2);
   print fact(j);
   print j;
   }

w = g;


print w;

