def g(a,b) a+b;
print g(2,3);
if not x eq 6 then {
oo = if  x lt 6 then 
  {(4*(1+2)*3*2+1)*π;}
else {
 f = for i = 3 to -1 step x-8 {
   f = f + √2*√(√81+4^2)*3*√(π-i);
   print(f);
   }}
   print f;
a[f]=√(f+2);
√a[f];;
} else {
u=3^2 + 4^2;
√u;
}

w = 1+2+3+4+5+6+7+8+9;
v = 45 - w;
z = 60°;
zz = z®;
c=cos(z);
s=sin(z);
k = cos(39)^2 + sin(39)^2;
print k;
cs = cos(sin(23));
e = ln(exp(1)^4);
s = √(1 - cos(4)^2);
ss = sin(4);

